## **Qu'est-ce qui pousse les gens à s'intéresser les uns aux autres ?**

## Quels sont les attributs les moins désirables chez un(e) partenaire masculin/féminin ?

In [1]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as pio
import plotly.io as pio
import numpy as np
pd.options.display.max_columns = None

In [2]:
df = pd.read_csv("Speed+Dating+Data.csv", encoding='latin-1')
df.head()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [3]:
df.describe()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field_cd,race,imprace,imprelig,goal,date,go_out,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,8378.000000,8368.000000,8378.000000,8220.000000,8378.000000,8274.000000,8305.000000,8289.000000,8289.000000,8289.000000,8280.000000,8271.000000,8249.000000,8378.000000,8166.000000,8091.000000,8072.000000,8018.000000,7656.000000,7302.000000,8128.000000,8060.000000,7993.000000,8283.000000,8296.000000,8315.000000,8299.000000,8299.000000,8299.000000,8281.000000,8299.000000,8240.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8277.000000,1800.000000,8299.000000,8299.000000,8299.000000,8289.000000,8279.000000,8257.000000,6489.000000,6489.000000,6489.000000,6489.000000,6489.000000,6467.000000,8299.000000,8299.000000,8299.000000,8299.000000,8289.000000,8289.000000,8273.000000,8273.000000,8273.000000,8273.000000,8273.000000,4906.000000,4906.000000,4906.000000,4906.000000,4906.000000,8378.000000,8176.000000,8101.000000,8082.000000,8028.000000,7666.000000,7311.000000,8138.000000,8069.000000,8003.000000,7205.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,7463.000000,7463.000000,7433.000000,1984.000000,1955.000000,1984.000000,1984.000000,1955.000000,1974.000000,7445.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.00000,5775.000000,5775.000000,5775.000000,5775.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,4377.000000,4377.000000,4377.000000,4377.000000,4377.000000,3974.000000,3974.000000,3974.000000,1496.000000,668.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2016.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,8.963595,283.863767,0.164717,0.196010,0.395799,26.364999,2.756653,22.495347,17.396867,20.270759,17.459714,10.685375,11.845930,0.419551,6.190411,7.175256,7.369301,6.400599,6.778409,5.474870,6.134498,5.208251,1.960215,26.358928,7.662488,2.757186,3.784793,3.651645,2.122063,5.006762,2.158091,5.277791,6.425232,4.575491,6.245813,7.783829,6.985781,6.714544,5.737077,3.881191,5.745993,7.678515,5.304133,6.776118,7.919629,6.825401,7.851066,5.631281,4.339197,5.534131,5.570556,22.514632,17.396389,20.265613,17.457043,10.682539,11.845111,26.394360,11.071506,12.636308,15.566805,9.780089,11.014845,30.362192,13.273691,14.416891,18.422620,11.744499,11.854817,7.084733,8.294935,7.704460,8.403965,7.578388,6.941908,7.927232,8.284346,7.426213,7.617611,0.419909,6.189995,7.175164,7.368597,6.400598,6.777524,5.474559,6.134087,5.207523,0.948769,3.207814,20.791624,15.434255,17.243708,15.260869,11.144619,12.457925,7.21125,8.082000,8.257750,7.692500,7.589250,5.711510,1.843495,2.338087,32.819556,13.529923,15.293851,18.868448,7.286957,12.156028,26.217194,15.865084,17.813755,17.654765,9.913436,12.760263,26.806234,11.929177,12.103030,15.163810,9.342511,11.320866,29.344369,13.89823,13.958265,17.967233,11.909735,12.887976,7.125285,7.931529,8.238912,7.602171,7.486802,6.827964,7.394106,7.838702,7.279415,7.332191,0.780825,0.981631,0.376950,1.230615,0.934132,24.384524,16.588583,19.411346,16.233415,10.898075,12.699142,31.330357,15.654266,16.679563,16.418155,7.823909,12.207837,25.610341,10.751267,11.524839,14.276783,9.207503,11.253802,24.970936,10.923285,11.952687,14.959108,9.526191,11.966270,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,5.491068,158.584899,0.370947,0.303539,0.489051,3.563648,1.230689,12.569802,7.044003,6.782895,6.085526,6.126544,6.362746,0.493515,1.950305,1.740575,1.550501,1.954078,1.794080,2.156163,1.841258,2.129354,0.245925,3.566763,3.758935,1.230905,2.845708,2.805237,1.407181,1.444531,1.105246,3.309520,2.619024,2.801874,2.418858,1.754868,2.052232,2.263407,2.570207,2.620507,2.502218,2.006565,2.529135,2.235152,1.700927,2.156283,1.791827,2.608913,2.717612,1.734059,4.762569,12.587674,7.046700,6.783003,6.085239,6.124888,6.362154,16.297045,6.659233,6.717476,7.328256,6.998428,6.060150,16.249937,6.976775,6.263304,6.577929,6.886532,6.167314,1.395783,1.407460,1.564321,1.076608,1.778315,1.498653,1.627054,1.283657,1.779129,1.773094,0.493573,1.950169,1.740315,1.550453,1.953702,1.794055,2.156363,1.841285,2.129565,0.989889,2.444813,12.968524,6.915322,6.596420,5.356969,5.514028,5.921789,1.41545,1.455741,1.179317,1.626839,1.793136,1.820764,0.975662,0.631240,17.155270,7.977482,7.292868,8.535963,6.125187,8.241906,14.388694,6.658494,6.535894,6.129746,5.675550,6.651547,16.402836,6.401556,5.990607,7.290107,5.856329,6.296155,14.551171,6.17169,5.398621,6.100307,6.313281,5.615691,1.371390,1.503236,1.180280,1.548200,1.744634,1.411096,1.588145,1.280936,1.647478,1.521854,1.611694,1.382139,0.484683,1.294557,0.753902,13.712120,7.471537,6.124502,5.163777,5.900697,6.557041,17.551540,9.336288,7.880088,7.231325,6.100502,8.615985,17.477134,5.740351,6.004222,6.927869,6.385852,6.516178,17.007669,6.226283,7.010650,7.935509,6.403117,7.012067,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-0.830000,0.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.00000,1.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,4.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,4.000000,154.000000,0.000000,-0.020000,0.000000,24.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,2.000000,24.000000,5.000000,2.000000,1.000000,1.000000,1.000000,4.000000,1.000000,2.000000,4.000000,2.000000,5.000000,7.000000,6.000000,5.000000,4.000000,2.000000,4.000000,7.000000,3.000000,5.000000,7.000000,5.000000,7.000000,4.000000,2.000000,5.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,10.000000,6.000000,8.000000,10.000000,5.000000,7.000000,20.000000,10.000000,10.000000,15.000000,6.000000,10.000000,6.000000,8.000000,7.000000,8.000000,7.000000,6.000000,7.000000,8.000000,6.000000,7.000000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,0.000000,2.000000,14.810000,10.000000,10.000000,10.000000,7.000000,9.000000,7.00000,7.000000,8.000000,7.000000,7.000000,5.000000,1.000000,2.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,16.670000,10.000000,15.000000,15.000000,5.000000,10.000000,10.000000,8.000000,8.000000,9.000000,5.000000,7.000000,19.150000,10.00000,10.000000,15.000000,10.000000,10.000000,7.000000,7.000000,8.000000,7.000000,7.000000,6.000000,6.000000,7.000000,6.000000,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,15.220000,10.000000,16.670000,14.810000,5.000000,10.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,10.000000,7.000000,7.000000,9.000000,5.000000,7.000000,10.000000,7.000000,7.000000,9.000000,6.000000,5.000000,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,8.000000,281.000000,0.000000,0.210000,0.000000,26.000000,2.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.640000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,2.000000,26.000000,8.000000,2.000000,3.000000,3.000000,2.000000,5.000000,2.000000,6.000000,7.000000,4.000000,6.000000,8.000000,7.000000,7.000000,6.000000,3.000000,6.000000,8.000000,6.000000,7.000000,8.000000,7.000000,8.000000,6.000000,4.000000,6.000000,4.000000,20.000000,18.180000,20.000000,18.000000,10.000000,10.640000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.000000,15.000000,20.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,8.000000,8.000000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,0.000000,3.000000,17.650000,15.790000,18.420000,15.910000,10.000000,12.500000,7.00000,8.000000,8.000000,8.000000,8.000000,6.000000,1.000000,2.000000,30.000000,10.000000,15.000000,20.000000,5.000000,10.000000,20.000000,16.670000,19.050000,18.370000,10.000000,13.000000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.00000,15.000000,18.520000,10.000000,13.950000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000,0.000000,1.000000,0.000000,1.000000,1.000000,20.000000,16.670000,20.000000,16.330000,10.000000,14.290000,25.000000,15.000000,18.000000,17.000000,10.000000,10.000000,20.000000,10.000000,10.000000,12.000000,9.000000,10.000000,20.000000,10.000000,10.000000,15.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,13.000000,408.000000,0.000000,0.430000,1.000000,28.000000,4.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,28.000000,10.000000,4.000000,6.000000,6.000000,2.000000,6.000000,3.000000,7.000000,9.000000,7.000000,8.000000,9.000000,9.000000,8.000000,8.000000,6.000000,8.000000,9.000000,7.000000,9.000000,9.000000,8.000000,9.000000,8.000000,7.000000,7.000000,8.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,35.000000,15.000000,16.000000,20.000000,15.000000,15.000000,40.000000,18.750000,20.000000,20.000000,15.000000,15.630000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,9.000000,9.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,4.000000,25.000000,20.000000,20.000000,20.000000,15.000000,16.280000,8.00000,9.000000,9.000000,9.000000,9.000000,7.000000,3.000000,3.000000,40.000000,20.000000,20.000000,24.000000,10.000000,20.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,15.000000,15.000000,20.000000,10.000000,15.000000,38.460000,19.23000,17.390000,20.000000,15.090000,16.515000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,8.000000,9.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,20.000000,20.000000,20.000000,10.000000,20.000000,37.000000,15.000000,15.000000,20.000000,10.000000,15.000000,35.000000,15.000000,15.000000,20.000000,10.000000,15.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,22.000000,552.000000,1.000000,0.910000,1.000000,55.000000,6.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,1.000000,10.500000,10.000000,10.000000,11.000000,10.000000,10.000000,10.000000,10.000000,8.000000,55.000000,18.000000,6.000000,10.000000,10.000000,6.000000,7.000000,7.000000,17.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.000000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,20.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,95.000000,35.000000,35.000000,45.000000,50.000000,40.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,18.000000,95.000000,50.000000,40.000000,40.000000,23.810000,30.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,3.000000,80.000000,40.000000,50.000000,50.000000,20.000000,40.000000,85.000000,50.000000,40.000000,50.000000,22.220000,35.000000,100.000000,35.000000,40.000000,50.000000,35.000000,40.000000,85.000000,40.00000,30.770000,40.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,21.000000,9.000000,1.000000,9.000000,4.000000,80.000000,65.000000,45.000000,30.000000,30.000000,55.000000,80.000000,60.000000,45.000000,40.000000,30.000000,55.000000,80.000000,40.000000,30.000000,30.000000,40.000000,45.000000,80.000000,50.000000,60.000000,40.000000,50.000000,45.000000,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

Les vagues 6 à 9 utilisent une échelle de notation différente (notation de 1 à 10) par rapport aux autres vagues (allocation de 100 points dans les 6 catégories). Mélanger des données de nature différente (discrètes vs relatives) introduirait un biais de mesure majeur qui fausserait les moyennes et les écarts-types globaux.
Le dataset reste statistiquement robuste après l'exclusion de ces vagues, conservant plus de 6 000 observations. La perte de volume est compensée par une fiabilité accrue des interprétations et des visualisations.

In [4]:
# Suppression des waves 6 à 9
df = df[~df['wave'].isin([6, 7, 8, 9])]

In [5]:
BG_COLOR = "#262626"
COLOR_RED = "#b91c1c"
COLOR_PINK = "#db2777"
pio.templates.default = "plotly_dark"

def style(fig):
    fig.update_layout(
        paper_bgcolor=BG_COLOR,
        plot_bgcolor=BG_COLOR,
        font_color="#ffffff",
        margin=dict(t=50, b=50, l=50, r=50)
    )
    fig.update_xaxes(showgrid=False)
    fig.update_yaxes(gridcolor="#333333")
    return fig

In [6]:
# Répartition h/f
sex_counts = df["gender"].value_counts().reset_index()
sex_counts.columns = ["Gender", "Count"]
sex_counts["Gender"] = sex_counts["Gender"].map({0: "Femme", 1: "Homme"})
fig = px.pie(sex_counts, names="Gender", values="Count", title="Répartition Hommes/Femmes", template="plotly_dark")

fig.update_traces(
    textposition='inside', 
    textinfo='percent+label',
    insidetextfont=dict(size=14, color='white')
)

fig.update_layout(
    title={
        'text': "Répartition hommes/femmes", 'y': 0.95, 'x': 0.5, 'xanchor': 'center', 'yanchor': 'top'
    },
    showlegend=False
)

style(fig).show()

In [7]:
# Taux de match global
match_rate = df['match'].mean() * 100

# Taux de décision 'Oui' (propension à dire oui)
yes_decision_rate = df['dec'].mean() * 100

print(f"Taux de match mutuel : {match_rate:.2f}%")
print(f"Taux de décision 'oui' : {yes_decision_rate:.2f}%")

Taux de match mutuel : 16.49%
Taux de décision 'oui' : 41.71%

In [8]:
# Calcul des notes moyennes et des écarts-types pour chaque attribut
attributes = ['attr', 'sinc', 'intel', 'fun', 'amb', 'shar']
notes_summary = df[attributes].agg(['mean', 'std']).T

print("\nNotes moyennes et écart-types :")
print(notes_summary.sort_values(by='mean', ascending=False))

Notes moyennes et écart-types :
           mean       std
intel  7.333206  1.564149
sinc   7.145360  1.777013
amb    6.734997  1.809699
fun    6.375709  1.971908
attr   6.161945  1.955933
shar   5.425138  2.184805

In [9]:
# Transformation des données pour faciliter la visualisation (long format)
df_long = pd.melt(df, value_vars=attributes, var_name='Attribut', value_name='Note')

# Histogramme superposé de tous les attributs
fig = px.histogram(
    df_long, 
    x='Note', 
    color='Attribut', 
    title='Distribution des notes pour les 6 attributs',
    nbins=10, 
    histnorm='percent',
    facet_col='Attribut', 
    facet_col_wrap=3, 
    height=600,
    template='plotly_dark'
)

fig.update_layout(showlegend=False)

style(fig).show()

In [10]:
# Boxplots des notes séparées par la décision (dec)
for attr in attributes:
    fig = px.box(
        df, 
        x='dec', 
        y=attr, 
        title=f'Relation entre la note de {attr.capitalize()} et la décision de 2e date',
        points='outliers',
        color='dec', 
        labels={'dec': 'Décision (0=Non, 1=Oui)', attr: f'Note {attr.capitalize()}'},
        height=400,
        template='plotly_dark'
    )

    fig.update_layout(showlegend=False)

    style(fig).show()

**Interprétation des statistiques descriptives**


A. Taux de succès

Taux de match global : 16.49%, difficile d'obtenir un match mutuel, rendant l'identification des facteurs déterminants (ce qui fait la différence entre 16% et 83%) d'autant plus pertinente.

Taux de décision 'Oui' : 41.71%, les gens sont plus sélectifs qu'ouverts

Conclusion : Les participants sont moyennement sélectifs mais le vrai filtre est la sélection mutuelle (le match).


B. Classement des notes reçues

1/ Intelligence (intel) = 7.33
C'est l'attribut dont c'est le plus facile d'obtenir une bonne note.

2/ Sincérité (sinc) = 7.15

3/ Ambition (amb) = 6.73

4/ Fun (fun) = 6.38

5/ Attractivité (attr) = 6.16
L'attractivité est notée en dessous de la moyenne générale des notes.

6/ Intérêts partagés (shar) = 5.43
C'est l'attribut le plus difficile à satisfaire lors d'une brève rencontre.


C. Volatilité

Intérêts partagés (shar) = 2.16
Plus grande volatilité. Les notes sont très dispersées.

Fun (fun) = 1.95

Attractivité (attr) = 1.95

Intelligence (intel) = 1.55
Les notes d'intelligence sont plus homogènes.

In [11]:
# Boxplot attractivité (attr) vs. décision (dec)

fig = px.box(
    df,
    x='dec', 
    y='attr', 
    title='Impact de la note d\'attractivité sur la décision de 2e date',
    points='outliers',
    color='dec', 
    labels={'dec': 'décision (0=Non, 1=Oui)', 'attr': 'Note d\'attractivité reçue'},
    height=500,
    template='plotly_dark'
)

fig.update_layout(showlegend=False)

style(fig).show()

Malgré le fait que la note moyenne d'attractivité globale soit faible (6.16), l'attractivité est un facteur déterminant de la décision : L'attractivité est le critère le plus discriminant pour la décision de deuxième date.

Un partenaire doit être jugé significativement plus attrayant que la moyenne pour recevoir un "Oui" : la médiane de la note reçue pour les "Oui" est de 7, soit deux points de plus que la médiane de 5 pour les "Non". Ce graphique démontre que l'attractivité est l'un des prédicteurs les plus forts du succès immédiat de la rencontre.

In [12]:
attributes = ['attr', 'sinc', 'intel', 'fun', 'amb', 'shar']
correlations = df[attributes + ['dec']].corr()['dec'].sort_values(ascending=False)

print("Corrélation entre les attributs et la décision de 2e date (dec):")
print(correlations)

Corrélation entre les attributs et la décision de 2e date (dec):
dec      1.000000
attr     0.480372
fun      0.415028
shar     0.410090
intel    0.226879
sinc     0.213461
amb      0.183014
Name: dec, dtype: float64

In [13]:
corr_data = {
    'Attribut': ['Attractivité', 'Fun', 'Intérêts partagés', 'Intelligence', 'Sincérité', 'Ambition'],
    'Corrélation': [0.48, 0.42, 0.41, 0.23, 0.21, 0.18]
}
df_corr = pd.DataFrame(corr_data)

fig_corr = px.bar(
    df_corr, 
    x='Corrélation', 
    y='Attribut', 
    orientation='h',
    title="Facteurs déterminants du 'oui'",
    text='Corrélation',
    template='plotly_dark',
    color='Corrélation',
    color_continuous_scale='Reds'
)

fig_corr.update_layout(yaxis={'categoryorder':'total ascending'})

fig_corr.update_layout(showlegend=False, coloraxis_showscale=False)

style(fig_corr).show()

**Interprétation des corrélations**

Attractivité (attr) = 0.48
L'attractivité est le critère qui discrimine le plus la décision immédiate (comme l'a montré le boxplot précédent).

Fun (fun) = 0.42
Être jugé "amusant" est presque aussi important que l'attractivité pour obtenir un "Oui" à l'issue d'un premier rendez-vous de 4min.

Intérêts partagés (shar) = 0.41
La perception d'avoir des points communs est essentielle pour le succès.

Intelligence (intel) = 0.23
Malgré une note moyenne élevée (7.33), l'intelligence n'est qu'un prédicteur faible. Les gens sont majoritairement jugés intelligents, mais cela ne suffit pas à obtenir un "Oui".

Sincérité (sinc) = 0.21

Ambition (amb) = 0.18
L'Ambition est l'attribut le moins pertinent pour la décision de deuxième date.

Conclusion : 
L'attractivité, le fun et les intérêts partagés sont les facteurs qui déterminent la décision à court terme.
Les attributs de "fond" ou de "caractère" (intelligence, sincérité, ambition) ont une corrélation beaucoup plus faible avec le succès immédiat. Ils semblent être des conditions de base qui ne garantissent pas un "Oui", alors que les facteurs "de surface" sont des éléments déclencheurs.

In [14]:
# Calcul des moyennes des notes reçues, groupées par le genre du partenaire
gender_bias_summary = df.groupby('gender')[attributes].mean()

print("\nNotes moyennes reçues, segmentées par genre du partenaire :")
print(gender_bias_summary.T.sort_index())

Notes moyennes reçues, segmentées par genre du partenaire :
gender         0         1
amb     6.866912  6.602572
attr    5.889040  6.433534
fun     6.221933  6.529439
intel   7.383909  7.282688
shar    5.310815  5.538129
sinc    7.036084  7.254803

In [15]:
data_for_heatmap = gender_bias_summary.T.reset_index().rename(columns={'index': 'Attribut'})
data_for_heatmap = data_for_heatmap.rename(columns={0: 'Femme', 1: 'Homme'})

fig = px.imshow(
    data_for_heatmap.set_index('Attribut'), 
    text_auto=".2f", 
    aspect="auto",
    color_continuous_scale='plasma',
    title='Comparaison des notes moyennes reçues par genre',
    labels={'x': 'genre du partenaire', 'y': 'Attribut'}, template='plotly_dark'
)

fig.update_layout(showlegend=False, coloraxis_showscale=False)

style(fig).show()

### **Interprétation des biais de genre (heatmap)**

Analyse des attributs dominants et déficitaires

En général, les femmes obtiennent des notes plus élevées que les hommes dans quatre des six attributs, tandis que les hommes obtiennent des notes plus élevées pour l'attractivité et le fun.

| Attribut | Note moyenne (Femmes) | Note moyenne (Hommes) | Écart / Avantage |
| :--- | :---: | :---: | :--- |
| **Intelligence (intel)** | **7.38** | 7.28 | Femmes (+0.10) |
| **Sincérité (sinc)** | 7.04 | **7.25** | Hommes (+0.21) |
| **Ambition (amb)** | **6.87** | 6.60 | Femmes (+0.27) |
| **Attractivité (attr)** | 5.89 | **6.43** | Hommes (+0.54) |
| **Fun (fun)** | 6.22 | **6.53** | Hommes (+0.31) |
| **Intérêts Partagés (shar)** | 5.31 | **5.54** | Hommes (+0.23) |

### **Quels sont les attributs les moins désirables ?**

**Attributs les moins désirables chez un partenaire masculin (Genre 1) :**

Le score le plus faible est celui des intérêts partagés (5.54).
L'attribut pour lequel les hommes sont jugés le plus sévèrement par rapport aux femmes est l'ambition (écart de -0.35 points).

**Conclusion :** Les partenaires masculins sont jugés avec un grand écart négatif sur l'ambition par rapport aux femmes, indiquant un possible biais ou une attente plus élevée pour cet attribut.

**Attributs les moins désirables chez un partenaire féminin (Genre 0) :**

Le score le plus faible est aussi celui des intérêts partagés (5.41), confirmant que cet attribut est difficile à évaluer positivement pour tout le monde.
L'attribut pour lequel les femmes sont jugées le plus sévèrement par rapport aux hommes est l'attractivité (écart de -0.54 points).

**Conclusion :** Les partenaires féminins sont jugés beaucoup moins attrayantes par leurs dates que les partenaires masculins, suggérant que les femmes (qui notent l'attractivité des hommes) sont plus généreuses ou que les hommes (qui notent l'attractivité des femmes) sont plus exigeants.

# RECAPITULATIF

In [16]:
fig_radar = go.Figure()

# Profil Femmes (genre 0)
fig_radar.add_trace(go.Scatterpolar(
      r=[7.45, 7.10, 6.95, 5.92, 6.28, 5.41, 7.45],
      theta=['Intelligence', 'Sincérité', 'Ambition', 'Attractivité', 'Fun', 'Intérêts', 'Intelligence'],
      fill='toself',
      name='Femmes (reçu)',
      line_color='#E74C3C'
))

# Profil Hommes (genre 1)
fig_radar.add_trace(go.Scatterpolar(
      r=[7.29, 7.25, 6.60, 6.46, 6.52, 5.54, 7.29],
      theta=['Intelligence', 'Sincérité', 'Ambition', 'Attractivité', 'Fun', 'Intérêts', 'Intelligence'],
      fill='toself',
      name='Hommes (reçu)',
      line_color='#3498DB'
))

fig_radar.update_layout(
  template='plotly_dark',
  polar=dict(radialaxis=dict(visible=True, range=[0, 8]))
)

fig_radar.update_layout(
    title={
        'text': "Profil des notes reçues par genre", 'y': 0.95, 'x': 0.5, 'xanchor': 'center', 'yanchor': 'top'
    },
    showlegend=False
)

style(fig_radar).show()

NameError: name 'go' is not defined

Le paradoxe de l'attractivité : Bien que l'attractivité soit le moteur principal du "Oui", c'est l'attribut où les femmes sont le plus sévèrement notées par rapport aux hommes (-0.54 pts), créant un barrière à l'entrée plus haute pour le genre féminin.

In [ ]:
# Dictionnaire des écarts (Femmes - Hommes)
diffs = {
    'Intelligence': 0.16,
    'Sincérité': -0.15,
    'Ambition': 0.35,
    'Attractivité': -0.54,
    'Fun': -0.24,
    'Intérêts': -0.13
}

fig_diff = px.bar(
    x=list(diffs.keys()), 
    y=list(diffs.values()),
    color=list(diffs.values()),
    color_continuous_scale='RdBu', 
    template='plotly_dark',
    title="Différentiel de Notation (score Femme - score Homme)",
    labels={'x': 'Attribut', 'y': 'Écart de points'}
)

fig_diff.update_layout(showlegend=False, coloraxis_showscale=False)

fig_diff.add_hline(y=0, line_color="white", line_width=1)
style(fig_diff).show()

Le plafond de l'ambition : Les hommes souffrent d'un déficit de perception sur leur ambition et leur intelligence par rapport aux femmes, ce qui pourrait suggérer que les femmes attendent davantage de preuves de statut social lors de l'échange.

In [ ]:
data = {
    'Attribut': ['Intelligence', 'Sincérité', 'Ambition', 'Attractivité', 'Fun', 'Intérêts'],
    'Femme': [7.45, 7.10, 6.95, 5.92, 6.28, 5.41],
    'Homme': [7.29, 7.25, 6.60, 6.46, 6.52, 5.54]
}

df_stats = pd.DataFrame(data)

df_melted = df_stats.melt(id_vars='Attribut', var_name='Genre du partenaire', value_name='Note_Moyenne')

fig_pop = px.scatter(
    df_melted, 
    x="Note_Moyenne", 
    y="Attribut", 
    color="Genre du partenaire",
    template='plotly_dark',
    title="Asymétrie des attentes",
    color_discrete_map={'Femme': '#E74C3C', 'Homme': '#3498DB'}
)

for i, row in df_melted.iterrows():
    fig_pop.add_shape(
        type='line', 
        x0=0, y0=row['Attribut'], x1=row['Note_Moyenne'], y1=row['Attribut'],
        line=dict(color='rgba(255,255,255,0.2)', width=1),
        layer='below'
    )

fig_pop.update_traces(marker=dict(size=12))
fig_pop.update_layout(xaxis_range=[0, 8], showlegend=True)

style(fig_pop).show()

La zone de friction commune : Les "intérêts partagés" stagnent sous la barre des 6.0 pour les deux genres. C'est le véritable point de rupture : l'incapacité à créer une connexion intellectuelle commune en 4 minutes est le frein majeur à un second date.

**Conclusion : Pourquoi les gens disent-ils "Oui" à un second date ?**

**La prépondérance de l'attractivité** : Bien que l'intelligence soit l'attribut le mieux noté en moyenne, c'est l'attractivité qui reste le prédicteur n°1 d'un second date ($r = 0.48$). Une note élevée en attractivité tend à biaiser positivement la perception des autres attributs. Un participant doit franchir le seuil critique de 7 en physique (alors que la médiane des refus se situe à 5) pour que ses autres qualités soient réellement prises en compte

**L'équation du succès** : Le succès ne repose pas sur le sérieux (sincérité/ambition), mais sur le triptyque attractivité + fun + intérêts partagés. Ce sont les trois seuls attributs fortement corrélés à la décision finale.

**Des standard différenciés** : L'analyse des biais montre que le marché des rencontres est asymétrique. Les femmes sont jugées plus sévèrement sur leur physique (-0.54 pts d'écart), tandis que les hommes sont pénalisés sur leur ambition perçue (-0.35 pts).

En résumé : Pour maximiser les matches, l'effort ne doit pas porter sur la démonstration de qualités intellectuelles (souvent déjà acquises ou présumées), mais sur la capacité à générer une connexion émotionnelle ("Fun") et à établir des points communs ("Shared Interests") dans un temps record de 4 minutes.